"""
Layer 2 GraphState — Store & Listing Pipeline
"""

from typing import TypedDict, List, Optional
from pydantic import BaseModel


class ShopifyListing(BaseModel):
    """A fully prepared Shopify product ready to publish."""
    # ── Source (from Layer 1 / CJ API) ──────────────────────────────────────
    cj_pid: str
    supplier_price: float
    suggested_retail: float = 0.0
    original_title: str
    image_urls: List[str]
    video_urls: List[str] = []           # Real playable video URLs from CJ
    variants: List[dict] = []            # Color/size variants from CJ
    trend_keyword: str
    category: str = ""
    collection: str = ""                 # Shopify collection name from Layer 1
    sub_collection: str = ""             # Sub-collection for better organization
    subcategory: str = ""                # Alternative name for sub-collection

    # ── Generated by ListingGenerator (LLM) ─────────────────────────────────
    shopify_title: str = ""
    shopify_description: str = ""        # HTML body
    bullet_points: List[str] = []
    tags: List[str] = []                 # LLM-generated tags
    shopify_tags: List[str] = []         # Explicit Shopify tags (from JSON or combined)
    seo_title: str = ""
    seo_description: str = ""            # Meta description (max 320 chars)

    # ── Set by PriceOptimizer ───────────────────────────────────────────────
    retail_price: float = 0.0
    compare_at_price: float = 0.0        # "Was" price for psychological pricing
    margin_pct: float = 0.0

    # ── Set by ImageAgent ───────────────────────────────────────────────────
    processed_image_urls: List[str] = []
    processed_video_urls: List[str] = [] # Local paths to downloaded videos

    # ── Set by StorePublisher ──────────────────────────────────────────────
    shopify_product_id: Optional[str] = None
    shopify_product_url: Optional[str] = None
    published: bool = False

    # ── Additional Metadata (from Layer 1) ──────────────────────────────────
    cj_product_url: Optional[str] = None      # CJ product detail URL
    discovery_date: Optional[str] = None      # When product was discovered
    source: Optional[str] = None              # Source of the product (e.g., "seed")
    region: Optional[str] = None              # Region info
    region_label: Optional[str] = None        # Region label
    rating: Optional[float] = None            # CJ product rating
    orders_count: Optional[int] = None        # CJ orders count
    shipping_days: Optional[int] = None       # Shipping days from CJ
    trend_score: Optional[float] = None       # Trend score from Layer 1

    # ── Computed Fields (optional) ──────────────────────────────────────────
    @property
    def all_tags(self) -> List[str]:
        """Combined tags from all sources, deduplicated."""
        combined = []

        # Add LLM-generated tags
        if self.tags:
            combined.extend(self.tags)

        # Add Shopify-specific tags
        if self.shopify_tags:
            combined.extend(self.shopify_tags)

        # Add collection as tag
        if self.collection:
            collection_tag = f"collection:{self.collection}"
            combined.append(collection_tag)

        # Add sub-collection as tag
        if self.sub_collection:
            sub_tag = f"sub:{self.sub_collection}"
            combined.append(sub_tag)
        elif self.subcategory:
            sub_tag = f"sub:{self.subcategory}"
            combined.append(sub_tag)

        # Add category as tag
        if self.category:
            category_tag = f"category:{self.category}"
            combined.append(category_tag)

        # Deduplicate while preserving order
        seen = set()
        unique_tags = []
        for tag in combined:
            if tag and tag not in seen:
                seen.add(tag)
                unique_tags.append(tag)

        return unique_tags

    @property
    def margin_amount(self) -> float:
        """Calculate profit margin in dollars."""
        return self.retail_price - self.supplier_price

    @property
    def margin_percentage(self) -> float:
        """Calculate profit margin as percentage."""
        if self.retail_price > 0:
            return (self.margin_amount / self.retail_price) * 100
        return 0.0

    @property
    def formatted_price(self) -> str:
        """Return retail price formatted as currency."""
        return f"${self.retail_price:.2f}"

    @property
    def variant_count(self) -> int:
        """Number of variants."""
        return len(self.variants)

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return self.model_dump(exclude_none=True)

    def __str__(self) -> str:
        """Human-readable string representation."""
        return f"ShopifyListing(title='{self.shopify_title[:50]}...', cj_pid={self.cj_pid}, price=${self.retail_price:.2f})"

    def __repr__(self) -> str:
        """Detailed representation."""
        return self.__str__()


class GraphState(TypedDict):
    """Layer 2 Graph State for the Store & Listing Pipeline."""

    # ── Input ──────────────────────────────────────────────────────────────
    winning_products: List[dict]        # From Layer 1 JSON output
    store_url: str                      # e.g., your-store.myshopify.com
    publish_immediately: bool           # Always True per your decision

    # ── Intermediate ──────────────────────────────────────────────────────
    listings: List[ShopifyListing]      # Built up through nodes
    priced_listings: List[ShopifyListing]
    image_ready_listings: List[ShopifyListing]

    # ── Output ────────────────────────────────────────────────────────────
    published_listings: List[ShopifyListing]
    failed_listings: List[dict]
    errors: List[str]